services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: '${PG_USER}'
      POSTGRES_PASSWORD: '${PG_PASSWORD}'
      AUTH_DB_NAME: '${AUTH_DB_NAME}'
      DB_NAME: '${DB_NAME}'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./Scripts:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
